[metadata]
name = hood
version = 0.0.0
author = Xiang Zhu
author_email = xzhu70@gmail.com
description = A hierarchical OO diag framework
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/xiangzhu70/hood
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GNU AGPLv3
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6

[options.packages.find]
where = src
